namespace Metal.NET;

/// <summary>A depth render target that serves as the output destination for depth pixels generated by a render pass.</summary>
public class MTLRenderPassDepthAttachmentDescriptor(nint nativePtr, NativeObjectOwnership ownership) : MTLRenderPassAttachmentDescriptor(nativePtr, ownership), INativeObject<MTLRenderPassDepthAttachmentDescriptor>
{
    #region INativeObject
    public static new MTLRenderPassDepthAttachmentDescriptor Null { get; } = new(0, NativeObjectOwnership.Borrowed);

    public static new MTLRenderPassDepthAttachmentDescriptor New(nint nativePtr, NativeObjectOwnership ownership)
    {
        return new(nativePtr, ownership);
    }
    #endregion

    public MTLRenderPassDepthAttachmentDescriptor() : this(ObjectiveC.AllocInit(MTLRenderPassDepthAttachmentDescriptorBindings.Class), NativeObjectOwnership.Managed)
    {
    }

    #region Specifying clearing value - Properties

    /// <summary>The depth to use when clearing the depth attachment.</summary>
    public double ClearDepth
    {
        get => ObjectiveC.MsgSendDouble(NativePtr, MTLRenderPassDepthAttachmentDescriptorBindings.ClearDepth);
        set => ObjectiveC.MsgSend(NativePtr, MTLRenderPassDepthAttachmentDescriptorBindings.SetClearDepth, value);
    }
    #endregion

    #region MSAA depth resolve - Properties

    /// <summary>The filter used for an MSAA depth resolve operation.</summary>
    public MTLMultisampleDepthResolveFilter DepthResolveFilter
    {
        get => (MTLMultisampleDepthResolveFilter)ObjectiveC.MsgSendULong(NativePtr, MTLRenderPassDepthAttachmentDescriptorBindings.DepthResolveFilter);
        set => ObjectiveC.MsgSend(NativePtr, MTLRenderPassDepthAttachmentDescriptorBindings.SetDepthResolveFilter, (nuint)value);
    }
    #endregion
}

file static class MTLRenderPassDepthAttachmentDescriptorBindings
{
    public static readonly nint Class = ObjectiveC.GetClass("MTLRenderPassDepthAttachmentDescriptor");

    public static readonly Selector ClearDepth = "clearDepth";

    public static readonly Selector DepthResolveFilter = "depthResolveFilter";

    public static readonly Selector SetClearDepth = "setClearDepth:";

    public static readonly Selector SetDepthResolveFilter = "setDepthResolveFilter:";
}
